package Interfaces;

import Classes.Game;
import javax.swing.ImageIcon;

/**
 *
 * @author Danna Star
 */
public class chooseMenu extends javax.swing.JFrame {
    ImageIcon pikachuPic = new ImageIcon("pikachu.png");
    ImageIcon pokemonPic = new ImageIcon("pokemonlogo.png");
    ImageIcon shinxPic = new ImageIcon("shinx1.png");
    ImageIcon fondoPic = new ImageIcon("fondo.jpg");
    /**
     * Creates new form InicialMenu
     */
    public chooseMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        pikachulabel1.setIcon(pikachuPic);
        pikachulabel1.setText("");
        pokemonLabel.setIcon(pokemonPic);
        pokemonLabel.setText("");
        shinxLabel1.setIcon(shinxPic);
        shinxLabel1.setText("");
        fondoLabel.setIcon(fondoPic);
        fondoLabel.setText("");
        fondoLabel1.setIcon(fondoPic);
        fondoLabel1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        shinx = new javax.swing.JButton();
        PanelPikachu = new javax.swing.JPanel();
        pokemonLabel = new javax.swing.JLabel();
        backButtom = new javax.swing.JButton();
        pikachu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pikachulabel1 = new javax.swing.JLabel();
        fondoLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        shinxLabel1 = new javax.swing.JLabel();
        fondoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(150, 10, 45));
        jPanel2.setForeground(new java.awt.Color(220, 10, 45));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shinx.setBackground(new java.awt.Color(222, 222, 222));
        shinx.setFont(new java.awt.Font("Pokemon Solid", 0, 18)); // NOI18N
        shinx.setForeground(new java.awt.Color(36, 36, 36));
        shinx.setText("Shinx");
        shinx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shinxActionPerformed(evt);
            }
        });
        jPanel2.add(shinx, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 240, 40));

        PanelPikachu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(PanelPikachu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        pokemonLabel.setText("jLabel3");
        jPanel2.add(pokemonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 360, 120));

        backButtom.setBackground(new java.awt.Color(222, 222, 222));
        backButtom.setFont(new java.awt.Font("Pokemon Solid", 0, 18)); // NOI18N
        backButtom.setForeground(new java.awt.Color(36, 36, 36));
        backButtom.setText("Atrás");
        backButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtomActionPerformed(evt);
            }
        });
        jPanel2.add(backButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, -1));

        pikachu.setBackground(new java.awt.Color(222, 222, 222));
        pikachu.setFont(new java.awt.Font("Pokemon Solid", 0, 18)); // NOI18N
        pikachu.setForeground(new java.awt.Color(36, 36, 36));
        pikachu.setText("Pikachu");
        pikachu.setToolTipText("");
        pikachu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pikachuActionPerformed(evt);
            }
        });
        jPanel2.add(pikachu, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, 240, 40));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pikachulabel1.setText("jLabel4");
        jPanel3.add(pikachulabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -20, 240, 410));

        fondoLabel1.setText("jLabel1");
        jPanel3.add(fondoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 290));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 240, 290));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shinxLabel1.setText("jLabel4");
        jPanel1.add(shinxLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 20, 320, 290));

        fondoLabel.setText("jLabel1");
        jPanel1.add(fondoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 0, 510, 290));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 240, 290));

        jLabel1.setFont(new java.awt.Font("Peace Sans", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(213, 213, 213));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Elige a tu mascota");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 540, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shinxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shinxActionPerformed
        Game mainGame= new Game(1);
        mainGame.prepareGame(1);
        
        //y se lleva a la página principal
        //sistem == una caracteristicas de shinx
        this.setVisible(false);
        MainMenu mainPage= new MainMenu();
        MainMenu.CurrentGame= mainGame;
        mainPage.setVisible(true);
    }//GEN-LAST:event_shinxActionPerformed

    private void pikachuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pikachuActionPerformed
        Game mainGame= new Game(2);
        mainGame.prepareGame(2);
        this.setVisible(false);
        MainMenu mainPage= new MainMenu();
        MainMenu.CurrentGame= mainGame;
        mainPage.setVisible(true);
    }//GEN-LAST:event_pikachuActionPerformed

    private void backButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtomActionPerformed
        this.setVisible(false);
        InicialMenu menu = new InicialMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_backButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chooseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chooseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chooseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chooseMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chooseMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPikachu;
    private javax.swing.JButton backButtom;
    private javax.swing.JLabel fondoLabel;
    private javax.swing.JLabel fondoLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton pikachu;
    private javax.swing.JLabel pikachulabel1;
    private javax.swing.JLabel pokemonLabel;
    private javax.swing.JButton shinx;
    private javax.swing.JLabel shinxLabel1;
    // End of variables declaration//GEN-END:variables
}
