package Interfaces;

import Classes.Game;
import Functions.Helpers;
import Functions.Pictures;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
/**
 *
 * @author Danna Star
 */
public class InicialMenu extends javax.swing.JFrame {
    Pictures pic= new Pictures();
    Helpers help = new Helpers();
    Clip mainClip;
    
    /* Creates new form InicialMenu
     */
    public InicialMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        pikachulabel1.setIcon(pic.getPikachuPic());
        pikachulabel1.setText("");
        pokemonLabel.setIcon(pic.getPokemonPic());
        pokemonLabel.setText("");
        shinxLabel1.setIcon(pic.getShinxPic());
        shinxLabel1.setText("");
        fondoLabel.setIcon(pic.getFondoPic());
        fondoLabel.setText("");
        
        mainClip=help.PlayMusic("menunormal.wav");
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        newGameButtom = new javax.swing.JButton();
        startGameButtom = new javax.swing.JButton();
        creditsButtom = new javax.swing.JButton();
        howToPlayButtom = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pokemonLabel = new javax.swing.JLabel();
        pikachulabel1 = new javax.swing.JLabel();
        shinxLabel1 = new javax.swing.JLabel();
        fondoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(600, 650));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(150, 10, 45));
        jPanel2.setForeground(new java.awt.Color(220, 10, 45));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newGameButtom.setBackground(new java.awt.Color(222, 222, 222));
        newGameButtom.setFont(new java.awt.Font("Pokemon Solid", 0, 18)); // NOI18N
        newGameButtom.setForeground(new java.awt.Color(36, 36, 36));
        newGameButtom.setText("Nuevo Juego");
        newGameButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtomActionPerformed(evt);
            }
        });
        jPanel2.add(newGameButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 530, 240, 40));

        startGameButtom.setBackground(new java.awt.Color(222, 222, 222));
        startGameButtom.setFont(new java.awt.Font("Pokemon Solid", 0, 18)); // NOI18N
        startGameButtom.setForeground(new java.awt.Color(36, 36, 36));
        startGameButtom.setText("Continuar Juego");
        startGameButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtomActionPerformed(evt);
            }
        });
        jPanel2.add(startGameButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 220, 40));

        creditsButtom.setBackground(new java.awt.Color(222, 222, 222));
        creditsButtom.setFont(new java.awt.Font("Pokemon Solid", 0, 18)); // NOI18N
        creditsButtom.setForeground(new java.awt.Color(36, 36, 36));
        creditsButtom.setText("Créditos");
        creditsButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditsButtomActionPerformed(evt);
            }
        });
        jPanel2.add(creditsButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 590, 220, 40));

        howToPlayButtom.setBackground(new java.awt.Color(222, 222, 222));
        howToPlayButtom.setFont(new java.awt.Font("Pokemon Solid", 0, 18)); // NOI18N
        howToPlayButtom.setForeground(new java.awt.Color(36, 36, 36));
        howToPlayButtom.setText("Cómo se Juega");
        howToPlayButtom.setToolTipText("");
        howToPlayButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                howToPlayButtomActionPerformed(evt);
            }
        });
        jPanel2.add(howToPlayButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 590, 240, 40));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Peace Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(16, 66, 126));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("tamagotchi");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 350, 80));

        pokemonLabel.setText("jLabel3");
        jPanel3.add(pokemonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 360, 120));

        pikachulabel1.setText("jLabel4");
        jPanel3.add(pikachulabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 240, 370));

        shinxLabel1.setText("jLabel4");
        jPanel3.add(shinxLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 290, 310));

        fondoLabel.setText("jLabel1");
        jPanel3.add(fondoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 490));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 490));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creditsButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditsButtomActionPerformed
        mainClip.stop();
        this.setVisible(false);
        Credits creditos = new Credits();
        creditos.setVisible(true);
    }//GEN-LAST:event_creditsButtomActionPerformed

    private void howToPlayButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_howToPlayButtomActionPerformed
        mainClip.stop();
        this.setVisible(false);
        HowToPlay howToPlayPage = new HowToPlay();
        howToPlayPage.setVisible(true);
    }//GEN-LAST:event_howToPlayButtomActionPerformed

    private void newGameButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtomActionPerformed
        
        Helpers help = new Helpers();
        String[] options= {"Sí","No"};
        if (help.saveExist()){
            int answer =JOptionPane.showOptionDialog(null, "¡Cuidado! Se borraran todos los datos guardados de su mascota.\nPresionse sí, si quiere continuar y reiniciar los valores del juego.\nPresione no, en el caso contrario.", "Confirmación de Inicio de Nuevo Juego", JOptionPane.YES_NO_CANCEL_OPTION, QUESTION_MESSAGE, null, options, options[0]);
            if  (answer==0){
                help.borrarArchivo();
                mainClip.stop();
                this.setVisible(false);
                chooseMenu selection = new chooseMenu(this.mainClip);
                selection.setVisible(true);
            }
        }
        else{
        this.setVisible(false);
        chooseMenu selection = new chooseMenu(this.mainClip);
        selection.setVisible(true);
        }
    }//GEN-LAST:event_newGameButtomActionPerformed

    private void startGameButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtomActionPerformed
        Helpers help = new Helpers();
        if (help.saveExist()) {
            Game auxGame= MainMenu.CurrentGame.LoadGame();
            if(auxGame!=null){
                mainClip.stop();
            MainMenu mainPage= new MainMenu();
            this.setVisible(false);
            mainPage.setVisible(true);
            MainMenu.CurrentGame=auxGame;
            }
        }else{
        JOptionPane.showMessageDialog(null, "No se ha  encontrado ninguna información previa del juego.\nInténtelo nuevamente, o inicie una nueva partida.", "Información", INFORMATION_MESSAGE, null);
        }
        
    }//GEN-LAST:event_startGameButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicialMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicialMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicialMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicialMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicialMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creditsButtom;
    private javax.swing.JLabel fondoLabel;
    private javax.swing.JButton howToPlayButtom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton newGameButtom;
    private javax.swing.JLabel pikachulabel1;
    private javax.swing.JLabel pokemonLabel;
    private javax.swing.JLabel shinxLabel1;
    private javax.swing.JButton startGameButtom;
    // End of variables declaration//GEN-END:variables
}
