package Interfaces;



/**
 *
 * @author Danna Star
 */
public class RecordPage extends javax.swing.JFrame {
    /**
     * Creates new form InicialMenu
     */
    public RecordPage() {
        initComponents();
        this.setLocationRelativeTo(null);
        texto.setText(MainMenu.CurrentGame.makeSummaryForRecord());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        PanelPikachu = new javax.swing.JPanel();
        backButtom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(150, 10, 45));
        jPanel2.setForeground(new java.awt.Color(220, 10, 45));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelPikachu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(PanelPikachu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        backButtom.setBackground(new java.awt.Color(222, 222, 222));
        backButtom.setFont(new java.awt.Font("Pokemon Solid", 0, 18)); // NOI18N
        backButtom.setForeground(new java.awt.Color(36, 36, 36));
        backButtom.setText("Atrás");
        backButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtomActionPerformed(evt);
            }
        });
        jPanel2.add(backButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 100, -1));

        jLabel1.setFont(new java.awt.Font("Peace Sans", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(213, 213, 213));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Historial de Regalos");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 540, 80));

        texto.setBackground(new java.awt.Color(0, 32, 42));
        texto.setColumns(20);
        texto.setFont(new java.awt.Font("Bodoni Bd BT", 0, 18)); // NOI18N
        texto.setForeground(new java.awt.Color(222, 218, 218));
        texto.setRows(5);
        texto.setMargin(new java.awt.Insets(6, 6, 6, 6));
        jScrollPane1.setViewportView(texto);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 520, 390));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtomActionPerformed
        this.setVisible(false);
        InicialMenu menu = new InicialMenu();
        menu.setVisible(true);
    }//GEN-LAST:event_backButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecordPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPikachu;
    private javax.swing.JButton backButtom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
