package Interfaces;

import Functions.Pictures;

/**
 *
 * @author Danna Star
 */
public class StorePage extends javax.swing.JFrame {
    Pictures pic= new Pictures();
    /**
     * Creates new form InicialMenu
     */
    public StorePage() {
        initComponents();
        this.setLocationRelativeTo(null);
        BayaAranjaLabel.setIcon(pic.getBayaAranjaPic());
        BayaCaquicLabel.setIcon(pic.getBayaCaquicPic());
        BayaEnigmaLabel.setIcon(pic.getBayaEnigmaPic());
        BayaZanamaLabel.setIcon(pic.getBayaZanamaPic());
        BayaZidraLabel.setIcon(pic.getBayaZidraPic());
        BayaZiuelaLabel.setIcon(pic.getBayaZiuelaPic());
        BayaZrezaLabel.setIcon(pic.getBayaZrezaPic());
        pokeballLabel.setIcon(pic.getPokeballPic());
        candyLabel.setIcon(pic.getCarameloPic());
        moneyLabelPic.setText("");
        moneyLabelPic.setIcon(pic.getWattPic());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BayaZidraLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        shinx = new javax.swing.JButton();
        PanelPikachu = new javax.swing.JPanel();
        tiendaTitle = new javax.swing.JLabel();
        shinx1 = new javax.swing.JButton();
        shinx2 = new javax.swing.JButton();
        shinx3 = new javax.swing.JButton();
        shinx4 = new javax.swing.JButton();
        shinx5 = new javax.swing.JButton();
        moneyLabelPic = new javax.swing.JLabel();
        shinx8 = new javax.swing.JButton();
        shinx6 = new javax.swing.JButton();
        shinx7 = new javax.swing.JButton();
        backButtom1 = new javax.swing.JButton();
        moneyLabel1 = new javax.swing.JLabel();
        candyLabel = new javax.swing.JLabel();
        BayaZidraLabel = new javax.swing.JLabel();
        pokeballLabel = new javax.swing.JLabel();
        BayaEnigmaLabel = new javax.swing.JLabel();
        BayaZrezaLabel = new javax.swing.JLabel();
        BayaZanamaLabel = new javax.swing.JLabel();
        BayaZiuelaLabel = new javax.swing.JLabel();
        BayaAranjaLabel = new javax.swing.JLabel();
        BayaCaquicLabel = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        BayaZidraLabel6.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(57, 90, 168));
        jPanel2.setForeground(new java.awt.Color(220, 10, 45));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        shinx.setBackground(new java.awt.Color(222, 222, 222));
        shinx.setFont(new java.awt.Font("Pokemon Solid", 0, 14)); // NOI18N
        shinx.setForeground(new java.awt.Color(36, 36, 36));
        shinx.setText("Baya Ziuela");
        shinx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shinxActionPerformed(evt);
            }
        });
        jPanel2.add(shinx, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 130, 40));

        PanelPikachu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(PanelPikachu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        tiendaTitle.setFont(new java.awt.Font("Peace Sans", 0, 60)); // NOI18N
        tiendaTitle.setForeground(new java.awt.Color(213, 213, 213));
        tiendaTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tiendaTitle.setText("Tienda");
        jPanel2.add(tiendaTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 230, 80));

        shinx1.setBackground(new java.awt.Color(222, 222, 222));
        shinx1.setFont(new java.awt.Font("Pokemon Solid", 0, 14)); // NOI18N
        shinx1.setForeground(new java.awt.Color(36, 36, 36));
        shinx1.setText("Baya Aranja");
        shinx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shinx1ActionPerformed(evt);
            }
        });
        jPanel2.add(shinx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 130, 40));

        shinx2.setBackground(new java.awt.Color(222, 222, 222));
        shinx2.setFont(new java.awt.Font("Pokemon Solid", 0, 14)); // NOI18N
        shinx2.setForeground(new java.awt.Color(36, 36, 36));
        shinx2.setText("Baya Caquic");
        shinx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shinx2ActionPerformed(evt);
            }
        });
        jPanel2.add(shinx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 130, 40));

        shinx3.setBackground(new java.awt.Color(222, 222, 222));
        shinx3.setFont(new java.awt.Font("Pokemon Solid", 0, 14)); // NOI18N
        shinx3.setForeground(new java.awt.Color(36, 36, 36));
        shinx3.setText("Caramelo raro");
        shinx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shinx3ActionPerformed(evt);
            }
        });
        jPanel2.add(shinx3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 590, 150, 40));

        shinx4.setBackground(new java.awt.Color(222, 222, 222));
        shinx4.setFont(new java.awt.Font("Pokemon Solid", 0, 14)); // NOI18N
        shinx4.setForeground(new java.awt.Color(36, 36, 36));
        shinx4.setText("Baya Zreza");
        shinx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shinx4ActionPerformed(evt);
            }
        });
        jPanel2.add(shinx4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 130, 40));

        shinx5.setBackground(new java.awt.Color(222, 222, 222));
        shinx5.setFont(new java.awt.Font("Pokemon Solid", 0, 14)); // NOI18N
        shinx5.setForeground(new java.awt.Color(36, 36, 36));
        shinx5.setText("Pokeball");
        shinx5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shinx5ActionPerformed(evt);
            }
        });
        jPanel2.add(shinx5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 130, 40));

        moneyLabelPic.setText("jLabel2");
        jPanel2.add(moneyLabelPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 40, 50));

        shinx8.setBackground(new java.awt.Color(222, 222, 222));
        shinx8.setFont(new java.awt.Font("Pokemon Solid", 0, 14)); // NOI18N
        shinx8.setForeground(new java.awt.Color(36, 36, 36));
        shinx8.setText("Baya Enigma");
        shinx8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shinx8ActionPerformed(evt);
            }
        });
        jPanel2.add(shinx8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 590, 130, 40));

        shinx6.setBackground(new java.awt.Color(222, 222, 222));
        shinx6.setFont(new java.awt.Font("Pokemon Solid", 0, 14)); // NOI18N
        shinx6.setForeground(new java.awt.Color(36, 36, 36));
        shinx6.setText("Baya Zanama");
        shinx6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shinx6ActionPerformed(evt);
            }
        });
        jPanel2.add(shinx6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 130, 40));

        shinx7.setBackground(new java.awt.Color(222, 222, 222));
        shinx7.setFont(new java.awt.Font("Pokemon Solid", 0, 14)); // NOI18N
        shinx7.setForeground(new java.awt.Color(36, 36, 36));
        shinx7.setText("Baya Zidra");
        shinx7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shinx7ActionPerformed(evt);
            }
        });
        jPanel2.add(shinx7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 130, 40));

        backButtom1.setBackground(new java.awt.Color(222, 222, 222));
        backButtom1.setFont(new java.awt.Font("Pokemon Solid", 0, 18)); // NOI18N
        backButtom1.setForeground(new java.awt.Color(36, 36, 36));
        backButtom1.setText("Atrás");
        backButtom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtom1ActionPerformed(evt);
            }
        });
        jPanel2.add(backButtom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 100, -1));

        moneyLabel1.setFont(new java.awt.Font("Peace Sans", 0, 17)); // NOI18N
        moneyLabel1.setForeground(new java.awt.Color(213, 213, 213));
        moneyLabel1.setText("...");
        jPanel2.add(moneyLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 100, 30));

        candyLabel.setText("jLabel2");
        jPanel2.add(candyLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 510, 90, 70));

        BayaZidraLabel.setText("jLabel2");
        jPanel2.add(BayaZidraLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 90, 90));

        pokeballLabel.setText("jLabel2");
        jPanel2.add(pokeballLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 90, 90));

        BayaEnigmaLabel.setText("jLabel2");
        jPanel2.add(BayaEnigmaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 90, 90));

        BayaZrezaLabel.setText("jLabel2");
        jPanel2.add(BayaZrezaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 90, 90));

        BayaZanamaLabel.setText("jLabel2");
        jPanel2.add(BayaZanamaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 310, 90, 90));

        BayaZiuelaLabel.setText("jLabel2");
        jPanel2.add(BayaZiuelaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 90, 90));

        BayaAranjaLabel.setText("jLabel2");
        jPanel2.add(BayaAranjaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 90, 90));

        BayaCaquicLabel.setText("jLabel2");
        jPanel2.add(BayaCaquicLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 90, 90));

        title2.setFont(new java.awt.Font("Peace Sans", 0, 18)); // NOI18N
        title2.setForeground(new java.awt.Color(213, 213, 213));
        title2.setText("Watts: ");
        jPanel2.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, -1, -1));

        jPanel1.setBackground(new java.awt.Color(97, 42, 7));
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 600, 40));

        jPanel3.setBackground(new java.awt.Color(97, 42, 7));
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 600, 40));

        jPanel4.setBackground(new java.awt.Color(97, 42, 7));
        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 600, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void shinxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shinxActionPerformed
        //En este boton crea el sistema o el juego principal con Shinx
        //y se lleva a la página principal
        //sistem == una caracteristicas de shinx
        this.setVisible(false);
        MainMenu mainPage= new MainMenu();
        mainPage.setVisible(true);
    }//GEN-LAST:event_shinxActionPerformed

    private void shinx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shinx1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shinx1ActionPerformed

    private void shinx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shinx2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shinx2ActionPerformed

    private void shinx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shinx3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shinx3ActionPerformed

    private void shinx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shinx4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shinx4ActionPerformed

    private void shinx5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shinx5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shinx5ActionPerformed

    private void shinx6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shinx6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shinx6ActionPerformed

    private void shinx7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shinx7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shinx7ActionPerformed

    private void shinx8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shinx8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shinx8ActionPerformed

    private void backButtom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtom1ActionPerformed
        MainMenu menu = new MainMenu();
        this.setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_backButtom1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StorePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StorePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StorePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StorePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StorePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BayaAranjaLabel;
    private javax.swing.JLabel BayaCaquicLabel;
    private javax.swing.JLabel BayaEnigmaLabel;
    private javax.swing.JLabel BayaZanamaLabel;
    private javax.swing.JLabel BayaZidraLabel;
    private javax.swing.JLabel BayaZidraLabel6;
    private javax.swing.JLabel BayaZiuelaLabel;
    private javax.swing.JLabel BayaZrezaLabel;
    private javax.swing.JPanel PanelPikachu;
    private javax.swing.JButton backButtom1;
    private javax.swing.JLabel candyLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel moneyLabel1;
    private javax.swing.JLabel moneyLabelPic;
    private javax.swing.JLabel pokeballLabel;
    private javax.swing.JButton shinx;
    private javax.swing.JButton shinx1;
    private javax.swing.JButton shinx2;
    private javax.swing.JButton shinx3;
    private javax.swing.JButton shinx4;
    private javax.swing.JButton shinx5;
    private javax.swing.JButton shinx6;
    private javax.swing.JButton shinx7;
    private javax.swing.JButton shinx8;
    private javax.swing.JLabel tiendaTitle;
    private javax.swing.JLabel title2;
    // End of variables declaration//GEN-END:variables
}
