/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import MiniGames.CartaAlta;
import javax.swing.JOptionPane;

/**
 *
 * @author Username
 */
public class WattsBet extends javax.swing.JFrame {

    /**
     * Creates new form JuegoCartaMasAlta
     */
    public WattsBet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        wattsBet = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        pruebaWatts = new javax.swing.JTextPane();
        betAccepted = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wattsBet.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                wattsBetStateChanged(evt);
            }
        });
        jPanel1.add(wattsBet, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 183, -1));

        jScrollPane1.setViewportView(pruebaWatts);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 273, -1));

        betAccepted.setText("Apostar!");
        betAccepted.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                betAcceptedStateChanged(evt);
            }
        });
        betAccepted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                betAcceptedActionPerformed(evt);
            }
        });
        jPanel1.add(betAccepted, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jLabel1.setText("     Juego de la carta mas alta pipipi!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void wattsBetStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_wattsBetStateChanged
        pruebaWatts.setText("El valor es: "+ wattsBet.getValue().toString());// TODO add your handling code here:
    }//GEN-LAST:event_wattsBetStateChanged

    private void betAcceptedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_betAcceptedActionPerformed
        int wattsBetted = (int) wattsBet.getValue();
        if (wattsBetted > 0 ) {
             CartaAlta Carta = new CartaAlta();
             int wattsGanados;
            wattsGanados = Carta.cartaAlta(wattsBetted);
            MainMenu.CurrentGame.increaseWatts(wattsGanados);
            this.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(null, "Debes ingresar un numero entre 0 y tus watts maximos");
        }
    }//GEN-LAST:event_betAcceptedActionPerformed

    private void betAcceptedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_betAcceptedStateChanged

    }//GEN-LAST:event_betAcceptedStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WattsBet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WattsBet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WattsBet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WattsBet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WattsBet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton betAccepted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane pruebaWatts;
    private javax.swing.JSpinner wattsBet;
    // End of variables declaration//GEN-END:variables
}
